### PR TITLE
Added pattern of hour Glass Closes #12

### LINKED ISSUE #12: Pattern Questions
Can you assign this issue to me Pattern problem in c++

### PR DESCRIPTION
**Pull request by iam-monu**
Addedpattern of hour Glass

### CODE REVIEW

**Comment by iam-monu** [comment]
I don't know how to link issue so I just pr it sorry for same

**Comment by dsrao711** [comment]
Looks good

**Review by dsrao711 — APPROVED** [review]
Approved

**Comment by iam-monu** [comment]
I have added some more patterns do check it and help me to win goodies! Thank you!

**Pull request merged**
