### PR TITLE
Add information on linked list and complexity

### LINKED ISSUE #7: Explain Linked Lists , Can we reverse a linked List in less than o(n)
- Explain LinkedList and use cases
- Can we reverse a linked List in less than o(n)
- Add your explanation in LinkedList.md file in LinkedList folder

### PR DESCRIPTION
**Pull request by neodark**
This PR adds information on linked list and algorithm complexity

Fixes #7

### CODE REVIEW

**Review by dsrao711 — CHANGES_REQUESTED** [review]
Do not add direct explanations from Geeks for Geeks. 
Plagiarism counts as invalid/spam 
Provide a detailed explanation in your own words

**Comment by neodark** [comment]
> Do not add direct explanations from Geeks for Geeks. Plagiarism counts as invalid/spam Provide a detailed explanation in your own words

Ok I will rephrase this.

**Comment by neodark** [comment]
Ok changes have been made, could you please review again and remove the invalid label. Thanks.

**Review by dsrao711 — APPROVED** [review]
Approved

**Pull request merged**
