### PR TITLE
Split_string_in_balanced_string  #21

### PR DESCRIPTION
**Pull request by Vaishnavi-Markunde**
Created solution for issue #21

### CODE REVIEW

**Review by dsrao711 — CHANGES_REQUESTED** [review]
The solution has to be in Python since the repo focuses on Python code.
Can you do this using Python?

**Comment by Vaishnavi-Markunde** [comment]
> The solution has to be in Python since the repo focuses on Python code. Can you do this using Python?

Okay I will do it

**Comment by Vaishnavi-Markunde** [comment]
> The solution has to be in Python since the repo focuses on Python code. Can you do this using Python?

I have uploaded the solution in python , do let me know if any changes have to be made

**Review by dsrao711 — APPROVED** [review]
approved

**Pull request merged**
